### PR TITLE
fix link in readme

### PR DESCRIPTION
**Pull request by macMikey**
in google section, link is broken

### CODE REVIEW

**Comment by macMikey** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by macMikey** [comment]
ummm, there is now a commit on main with my signature, for some reason, but the PR is still pending

**Comment by e-marchand** [comment]
Hi, the pr is ok. All is signed correctly.

Someone from 4d must review the change and accept/merge it
(If nobody do it I wii find someone or I will take a look)

**Comment by macMikey** [comment]
that's not the problem.
look at the graph (last commit on main, 9a71dfb6401e0b867bebe64ab17987bbc3cfe7b0)

**Comment by e-marchand** [comment]
This is how the signature is stored.
By accepting cla with the comment, it create a commit that store it

**Pull request merged**
