### PR TITLE
fix link in readme

### PR DESCRIPTION
**Pull request by macMikey**
in the google section, there is a broken link.

### CODE REVIEW

**Comment by macMikey** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by e-marchand** [comment]
recheck

**Comment by macMikey** [comment]
what does that mean? do you mean re-PR?

**Comment by e-marchand** [comment]
No worries
(Even a new pr will not work. We must find why the github process/action do not work anymore.)

**Comment by macMikey** [comment]
ok, ding me when you want to try, again

**Comment by e-marchand** [comment]
recheck

**Comment by macMikey** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by macMikey** [comment]
recheck

**Comment by e-marchand** [comment]
recheck

**Comment by e-marchand** [comment]
@macMikey 
hi, I think I have the issue 

The commit has been done with this account https://github.com/mustache-inc
see https://github.com/4d/4D-NetKit/pull/60/commits

The CLA must be signed (with the comment) by (all) commiters
and not the one that create the PullRequest

So yes maybe create a new pull request and commit with https://github.com/macMikey account instead
or  https://github.com/mustache-inc must comment here to sign the CLA

**Comment by macMikey** [comment]
i don't even now what mustache-inc is. i'll have to see if i can figure out what might be going on.

**Comment by macMikey** [comment]
i'm going to close this pr and try to re-issue it.

**Pull request closed without merging**
