### PR TITLE
Issue 63 token expiration not checked once it is issued

### PR DESCRIPTION
**Pull request by macMikey**
https://github.com/4d/4D-NetKit/issues/63
Per [this thread](https://discuss.4d.com/t/help-understanding-how-to-refresh-token-using-netkit/30881/6) on the forum, the token expire is not being checked.

### CODE REVIEW

**Comment by macMikey** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by macMikey** [comment]
recheck

**Comment by e-marchand** [comment]
the commit is from "[mustache-inc](https://github.com/macMikey/4D-NetKit/commits?author=mustache-inc)" account , so like other first PullRequest it must be signed by the commit author
(you have already signed as [macMikey](https://github.com/macMikey))

**Review by yannicktrinh — COMMENTED** [review]
Hello,

I think you can even write something like this:

`
return This._internals._oAuth2Provider.getToken()
`

Thanks for feedback

**Comment by macMikey** [comment]
@e-marchand 
i don't understand why github keeps misassigning the author to some other account. annoying.
on the PR, itself, we are not requesting the token, each time. by removing the **if** block, we are just triggering the check to see if it expired, which then causes the refresh token to be used to get a new access token.

@yannicktrinh
that's what you get if you remove the **if**. see the PR

**Comment by macMikey** [comment]
i'm going to close this PR, since the attribution is wrong, again, and try to resubmit it.

**Pull request closed without merging**
