### PR TITLE
Certificate auth improvements

### PR DESCRIPTION
**Pull request by SBlaserBossinfo**
@e-marchand fyi

### CODE REVIEW

**Comment by SBlaserBossinfo** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by e-marchand** [comment]
@SBlaserBossinfo Thanks you it seems ok and branch/commit will be more clean!!

@yannicktrinh this is a new PR with one commit now, I close the other one (due to CLA issue and merge commit)
as you say you will see with your ProjectOwner (and maybe review the fix requested here)

**Comment by fabrice-mainguene** [comment]
Seems to be an implementation of the [rfc7521](https://datatracker.ietf.org/doc/html/rfc7521)

**Comment by SBlaserBossinfo** [comment]
> Seems to be an implementation of the [rfc7521](https://datatracker.ietf.org/doc/html/rfc7521)
What is the roadmap here? What do you think when will this be available?

**Comment by yannicktrinh** [comment]
Merged in branch YT/Feature/OAuth2/4397 (before integration in Main)
Thanks for your feedback, your work and your patience too :)

**Pull request merged**
